### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by codegiter1018** [codegiter1018/protospace-38614#1]
# URL
https://protospace-38614.onrender.com/

**Comment by motomuun** [comment]
@codegiter1018 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー管理機能**

- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
「さん」まで表示されるように修正をお願いします。

**ユーザー詳細機能**

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
「ユーザー名」のところに正しいユーザー名が表示されるように修正をお願いします。
<img width="754" alt="スクリーンショット 2023-02-06 11 16 54" src="https://user-images.githubusercontent.com/65059944/216867998-9861ff8b-a92b-4161-a97f-7912fb207699.png">



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by codegiter1018** [comment]
確認頂き有難うございます。
修正し本番環境で確認もできましたので再度完了報告実施します。

**Comment by ghost** [comment]
@codegiter1018 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by codegiter1018** [comment]
ご確認有難うございます。了解しました！
